output_root: output
logging_root: logs

behavior:
  allow_degraded_start: true
  start_pause_key: ENTER
  quit_key: q

modules:
  paxini_force:
    enabled: true
    adapter: paxini_force
    allow_placeholder: false
    output_subdir: .
    initialize_command:
      - python
      - scripts/calibrate_dp_s2015.py
      - --config
      - config/default.yaml
    command:
      - python
      - scripts/log_paxini_force.py
      - --config
      - config/default.yaml
    workdir: .

left_file_name: left_sensor.jsonl
right_file_name: right_sensor.jsonl
print_human_readable: true

stream:
  sampling_hz: 30.0

calibration:
  file: config/dp_s2015_calibration.json
  tare_samples: 30

serial:
  port: AUTO
  serial_number: D4B86775660C
  baudrate: 921600
