output_root: sessions
logging_root: logs

behavior:
  allow_degraded_start: true
  start_pause_key: ENTER
  quit_key: q

modules:
  imu:
    enabled: true
    adapter: imu
    allow_placeholder: false
    output_subdir: imu
    initialize_command: null
    command:
      - python
      - scripts/log_d435i_pitch_roll.py
      - --config
      - config/default.yaml
    workdir: ../imu_pose_grasping

  paxini:
    enabled: true
    adapter: paxini_force
    allow_placeholder: false
    output_subdir: paxini
    initialize_command:
      - python
      - scripts/calibrate_dp_s2015.py
      - --config
      - config/default.json
    command:
      - python
      - scripts/log_paxini_force.py
      - --config
      - config/default.json
    workdir: ../paxini_force_grasping

  force6d:
    enabled: true
    adapter: force6d
    allow_placeholder: false
    output_subdir: force6d
    initialize_command:
      - python
      - scripts/zero_calibration.py
      - --config
      - config/default.json
    command:
      - python
      - scripts/read_data.py
      - --config
      - config/default.json
    workdir: ../6D_force_grasping
