camera_a:
  serial_no: ""
  camera_name: camera_a
  color_width: 1280
  color_height: 720
  color_fps: 15

camera_b:
  serial_no: ""
  camera_name: camera_b
  color_width: 1280
  color_height: 720
  color_fps: 15

driver:
  enable_depth: false
  enable_infra1: false
  enable_infra2: false
  enable_gyro: false
  enable_accel: false
  enable_pointcloud: false
